Model Selection

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
from sklearn.metrics import r2_score

In [2]:
dataset = pd.read_csv("dataset/Data.csv")
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

Splitting the dataset into training and test set

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [4]:
print(X_train)   

[[ 752904      10       1 ...       5       4       1]
 [1218860       1       1 ...       3       1       1]
 [ 411453       5       1 ...       3       1       1]
 ...
 [1214092       1       1 ...       1       1       1]
 [1303489       3       1 ...       2       1       1]
 [ 378275      10       9 ...       7       7       1]]


Multiple Linear Regression

In [5]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate(( y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))
r2_score(y_test, y_pred)

[[2.25 2.  ]
 [2.03 2.  ]
 [3.52 4.  ]
 [3.7  4.  ]
 [1.89 2.  ]
 [2.09 2.  ]
 [2.26 2.  ]
 [3.94 4.  ]
 [2.07 2.  ]
 [1.94 2.  ]
 [4.   4.  ]
 [2.17 2.  ]
 [4.23 4.  ]
 [2.04 2.  ]
 [2.22 2.  ]
 [2.7  2.  ]
 [3.58 4.  ]
 [4.11 4.  ]
 [4.21 4.  ]
 [2.18 2.  ]
 [2.03 2.  ]
 [2.11 2.  ]
 [3.12 4.  ]
 [1.99 2.  ]
 [3.83 4.  ]
 [3.9  4.  ]
 [2.2  2.  ]
 [1.92 2.  ]
 [2.1  2.  ]
 [3.74 4.  ]
 [1.88 2.  ]
 [4.31 4.  ]
 [4.59 4.  ]
 [2.07 2.  ]
 [2.05 2.  ]
 [2.07 2.  ]
 [3.83 4.  ]
 [3.63 4.  ]
 [2.05 2.  ]
 [3.9  4.  ]
 [2.26 2.  ]
 [2.43 2.  ]
 [2.01 2.  ]
 [1.96 2.  ]
 [1.88 2.  ]
 [2.13 2.  ]
 [1.97 2.  ]
 [4.23 4.  ]
 [2.13 2.  ]
 [2.11 2.  ]
 [3.77 4.  ]
 [2.15 2.  ]
 [3.49 4.  ]
 [2.13 2.  ]
 [2.18 2.  ]
 [2.31 2.  ]
 [3.8  4.  ]
 [3.48 2.  ]
 [2.4  2.  ]
 [3.88 4.  ]
 [1.96 2.  ]
 [1.98 2.  ]
 [2.02 2.  ]
 [1.99 2.  ]
 [2.07 2.  ]
 [1.96 2.  ]
 [1.97 2.  ]
 [2.09 2.  ]
 [3.64 4.  ]
 [2.84 4.  ]
 [1.94 2.  ]
 [2.05 2.  ]
 [1.92 2.  ]
 [2.07 2.  ]
 [2.32 2.  ]
 [2.13 2.  ]
 [3.8  4.  ]

0.8354489501242135

Polynomial Linear Regression

In [6]:
from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree=4)
X_poly = poly_reg.fit_transform(X_train)
regressor = LinearRegression()
regressor.fit(X_poly, y_train)
y_pred = regressor.predict(poly_reg.transform(X_test))
r2_score(y_test, y_pred)

0.6085483223694554

Decision Tree Model

In [7]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state=0)
regressor.fit(X_train, y_train)
r2_score(y_test, regressor.predict(X_test))

0.6535632183908047

Random Forest

In [8]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators=10, random_state=0)
regressor.fit(X_train, y_train)
r2_score(y_test, regressor.predict(X_test))

0.8447333333333333

Support Vector Regression (SVR)

In [9]:
from sklearn.preprocessing import StandardScaler
#for the SVN we need to reshape the y axis
y_reshaped = y.reshape(len(y), 1)

X_train_svr, X_test_svr, y_train_svr, y_test_svr = train_test_split(X, y_reshaped, test_size=0.2, random_state=0)
scaler_X = StandardScaler()
scaler_y = StandardScaler()
X_train_svr = scaler_X.fit_transform(X_train_svr)
y_train_svr = scaler_y.fit_transform(y_train_svr)

from sklearn.svm import SVR
regressor = SVR(kernel="rbf")
regressor.fit(X_train_svr, y_train_svr)

y_pred = scaler_y.inverse_transform(regressor.predict(scaler_X.transform(X_test_svr)))
    # r2_score(X_test_svr, y_)

c:\Python310\lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


ValueError: Expected 2D array, got 1D array instead:
array=[-0.62 -0.82  1.34  1.35 -0.71 -0.79 -0.76  1.42 -0.61 -0.69  1.47 -0.79
  1.31 -0.83 -0.65  0.61  1.48  1.29  1.33 -0.77 -0.81 -0.84  0.99 -0.77
  1.62  1.48 -0.75 -0.73 -0.75  1.72 -0.69  1.1   1.34 -0.83 -0.79 -0.83
  1.42  1.45 -0.8   1.33 -0.74 -0.31 -0.77 -0.71 -0.69 -0.81 -0.64  1.33
 -0.78 -0.73  1.43 -0.83  1.5  -0.75 -0.76 -0.67  1.33  1.4  -0.6   1.24
 -0.77 -0.73 -0.8  -0.8  -0.83 -0.77 -0.79 -0.77  1.48  0.9  -0.73 -0.69
 -0.74 -0.68 -0.7  -0.81  1.55 -0.78 -0.8  -0.76  1.35 -0.8   1.35 -0.78
 -0.7   1.33 -0.72  1.03  1.34 -0.4   1.47 -0.76  1.4   0.97  0.11  0.86
  1.37  1.29  0.73 -0.73 -0.69 -0.77  1.35  1.36 -0.81 -0.67  1.25  0.43
 -0.75 -0.67  1.36 -0.74 -0.82  1.26 -0.73  0.12 -0.73  0.71 -0.73 -0.77
 -0.75  1.52 -0.76 -0.75  1.34  1.32 -0.62  1.08 -0.77  1.41  0.23 -0.73
  1.48 -0.76 -0.74  1.21 -0.81].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.