Data Preprocessing Tools

Importing libraries

In [16]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Importing the dataset

In [17]:
dataset = pd.read_csv("dataset/sample_data.csv")
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

Count the number of missing data

In [18]:
nan_val = dataset.isna().sum()
print(nan_val)

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64


Taking care of the missing data

In [19]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")
X[:, 2:3] = np.round(imputer.fit_transform(X[:, 2:3]), 1) #Only the Salary  with 1 decimal place
X[:, 1:2] = np.round(imputer.fit_transform(X[:, 1:2])) #Only the Age  Column

Enconding categorical data

In [20]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
col_trans = ColumnTransformer(transformers=[("encoder", OneHotEncoder(), [0])], remainder="passthrough")
X = np.array(col_trans.fit_transform(X))

In [21]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.8]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 39.0 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


Enconding the Dependent Variable

In [22]:
from sklearn.preprocessing import LabelEncoder
label_en = LabelEncoder()
y = label_en.fit_transform(y)

In [23]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


Splitting the dataset into the Training set and Test set

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [25]:
X_train

array([[0.0, 0.0, 1.0, 39.0, 52000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.8],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object)

In [26]:
X_test

array([[0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [27]:
y_train

array([0, 1, 0, 0, 1, 1, 0, 1])

In [28]:
y_test

array([0, 1])

Feature Scaling

In [29]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train[:, 3:] = scaler.fit_transform(X_train[:, 3:])
X_test[:, 3:] = scaler.transform(X_test[:, 3:])

In [30]:
X_train

array([[0.0, 0.0, 1.0, -0.16347432065523887, -1.0781261965508206],
       [0.0, 1.0, 0.0, -0.018163813406137652, -0.07013001344412373],
       [1.0, 0.0, 0.0, 0.5630782155902672, 0.6335622055390376],
       [0.0, 0.0, 1.0, -0.3087848279043401, -0.3078664156103844],
       [0.0, 0.0, 1.0, -1.9072004076444533, -1.4204638769687923],
       [1.0, 0.0, 0.0, 1.144320244586672, 1.232653146270488],
       [0.0, 1.0, 0.0, 1.4349412590848745, 1.5749908266884596],
       [1.0, 0.0, 0.0, -0.7447163496516437, -0.5646196759238631]],
      dtype=object)

In [31]:
X_test

array([[0.0, 1.0, 0.0, -1.4712688858971497, -0.9069573563418347],
       [1.0, 0.0, 0.0, -0.45409533515344125, 0.20564010501657307]],
      dtype=object)